### ISSUE TITLE
Checklist support

### ISSUE THREAD

**Issue by dhbradshaw** [marimo-team/marimo#3149]
### Description

Love Marimo and am excited to follow the progress!  

When I'm writing markdown, I love to make checklists:

- [ ] They help me track progress
- [ ] They are fun
- [ ] They are a key part of work planning.

The fact that checklists aren't well supported in Marimo has me reverting back to vscode and Markdown when I'm doing certain kinds of work.

### Suggested solution

Here in Github, when I have the first item and press enter, the text for a second item appears.

I'm not sure what the ideal support for markdown checklists might be in Marimo, but at a minimum it would be nice if 

1. The next item were autogenerated when you press enter after writing the current item
2. The rendered markdown looked like a checkbox appropriately either filled or unfilled.

Additionally, it would be nice to have a hot key to toggle a checkmark while editing the markdown.

**Comment by mscolnick** [comment]
thanks for the request. i've added it https://github.com/marimo-team/marimo/pull/3151, it was super easy given its an extension of a dependency we already bring in

**Comment by dhbradshaw** [comment]
So cool 😎 thank you!
