### ISSUE TITLE
Multi-mode Vim support like Jupyterlab-Vim

### ISSUE THREAD

**Issue by anjiro** [marimo-team/marimo#931]
### Description

[Jupyterlab-Vim](https://github.com/jupyterlab-contrib/jupyterlab-vim) adds a "Jupyterlab Command Mode" which enables manipulation at the cell level. It's super nice and I'd love to see it implemented in Marimo.

### Suggested solution

Here's what Jupyterlab-Vim lists (copied verbatim):

---

**Please note that all keys are lowercase unless `Shift` is explicitly indicated.**
For example, `Y, Y` is two lowercase `y`s, `Shift-Y, Y` is one uppercase `Y` followed by a lowercase `y`.

Shortcuts this extension introduces:

### Vim Ex commands

| Command  | Action                     |
| -------- | -------------------------- |
| :w[rite] | Save Notebook              |
| :q[uit]  | Enter Jupyter command mode |

### Vim command bindings

| Chord           | Action                    |
| --------------- | ------------------------- |
| Ctrl-O, U       | Undo Cell Action          |
| -               | Split Cell at Cursor      |
| Ctrl-O, -       | Split Cell at Cursor      |
| Ctrl-O, D       | Cut Cell                  |
| Ctrl-O, Y       | Copy Cell                 |
| Ctrl-O, P       | Paste Cell                |
| Ctrl-Shift-J    | Extend Marked Cells Below |
| Ctrl-Shift-K    | Extend Marked Cells Above |
| Ctrl-O, O       | Insert Cell Below         |
| Ctrl-O, Ctrl-O  | Insert Cell Above         |
| Ctrl-J          | Select Cell Below         |
| Ctrl-K          | Select Cell Above         |
| Ctrl-O, G       | Select First Cell         |
| Ctrl-O, Ctrl-G  | Select Last Cell          |
| Ctrl-E          | Move Cell Down            |
| Ctrl-Y          | Move Cell Up              |
| Ctrl-O, Z, Z    | Center Cell               |
| Ctrl-G          | Show Tooltip              |
| Command/Ctrl-1  | Code Cell Mode            |
| Command/Ctrl-2  | Markdown Cell Mode        |
| Command/Ctrl-3  | Raw Cell Mode             |
| Shift-Escape    | Leave Vim Mode            |
| Escape, Ctrl-\[ | Exit Vim Insert Mode      |

### Jupyter command bindings

| Chord   | Action              |
| ------- | ------------------- |
| G, G    | Select First Cell   |
| Shift-G | Select Last Cell    |
| D, D    | Delete Cell         |
| Y, Y    | Yank (Copy) Cell    |
| P       | Paste Cell          |
| Shift-P | Paste Cell Above    |
| O       | Insert Cell         |
| Shift-O | Insert Cell Above   |
| U       | Undo Cell Action    |
| Ctrl-E  | Move Cells Down     |
| Ctrl-Y  | Move Cells Up       |
| Z, Z    | Center Cell         |
| Z, C    | Hide Code Cell      |
| Z, O    | Show Code Cell      |
| Z, M    | Hide All Code Cells |
| Z, R    | Show All Code Cells |

**Comment by akshayka** [comment]
Thanks for the feature request! I've used these bindings in the past, and they are nice.

Unfortunately we likely won't get to this soon, just because of a backlog of other tasks ahead of us. But I will keep this open for the future, and so that others can :+1: it if they'd also like to see these bindings implemented.

**Comment by manzt** [comment]
I'm starting to take a closer look at our Vim bindings. We likely won't support _every_ existing binding, but we’re aiming for incremental improvements.

With the recent command mode implementation in #5614, our current focus is to build out **command-mode-style bindings**. Here's what we're thinking so far:

### ✅ Planned

- [x] `d d` – Delete Cell*  #5664 #5670 
- [x] `g g` – Select First Cell #5636
- [x] `G` – Select Last Cell #5636
- [x] `y y` – Yank (Copy) Cell #5675
- [x] `p` – Paste Cell Below #5675
- [x] `P` – Paste Cell Above #5675
- [x] `o` – Insert Cell Below #5675
- [x] `O` – Insert Cell Above #5675
- [x] `u` – Undo Cell Action #5675

### ❌ Not Planned
`z z` – Center Cell  
`z c` – Hide Code Cell (use `⌘ h` toggle)  
`z o` – Show Code Cell (use `⌘ h` toggle)  
`z m` – Hide All Code Cells  
`z r` – Show All Code Cells  
`Ctrl-E` – Move Cells Down (will consider if we add regular shortcut)
`Ctrl-Y` – Move Cells Up (will consider if we add regular shortcut)

\* contains warning/confirmation step for potentially "expensive" deletions

**Comment by manzt** [comment]
Closing as completed. We’ve landed the core command-mode-style bindings in v0.14.11, and they should cover most workflows. We’re not aiming for full parity, but we’re open to specific follow-up requests. I’d like to see evidence of demand first, so please feel free to open targeted issues to help us understand what the community needs most!
